#!/bin/bash

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

chown -R gitlab-runner:gitlab-runner /home/gitlab-runner
if [ ! -d /home/gitlab-runner/.ssh ]; then mkdir -p /home/gitlab-runner/.ssh; fi
if [ ! -f /home/gitlab-runner/.ssh/config ]; then
    touch /home/gitlab-runner/.ssh/config
    echo -e "Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null" > /home/gitlab-runner/.ssh/config
fi
chmod 700 /home/gitlab-runner/.ssh
chmod 644 /home/gitlab-runner/.ssh/config

# gitlab-runner's config directory
CONFIG_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-${CONFIG_DIR}/config.toml}

# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-${CONFIG_DIR}/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

# launch gitlab-ci-multi-runner passing all arguments
exec gitlab-ci-multi-runner "$@"
